#ifndef ORGANOTYPICADHESIONECMCONCENTRATION_EXPORT_H 
#define ORGANOTYPICADHESIONECMCONCENTRATION_EXPORT_H

    #if defined(_WIN32)
      #ifdef OrganotypicAdhesionECMConcentration_EXPORTS
          #define ORGANOTYPICADHESIONECMCONCENTRATION_EXPORT __declspec(dllexport)
          #define ORGANOTYPICADHESIONECMCONCENTRATION_EXPIMP_TEMPLATE
      #else
          #define ORGANOTYPICADHESIONECMCONCENTRATION_EXPORT __declspec(dllimport)
          #define ORGANOTYPICADHESIONECMCONCENTRATION_EXPIMP_TEMPLATE extern
      #endif
    #else
         #define ORGANOTYPICADHESIONECMCONCENTRATION_EXPORT
         #define ORGANOTYPICADHESIONECMCONCENTRATION_EXPIMP_TEMPLATE
    #endif

#endif

