function [neighbours_struct,...
         index_all_tissue] = ...
    organotypic_neighbour_structure_compiler(...
                                neighbours_struct,...
                                binary_all_cells_from_pixels,...
                                cells_from_pixels,...
                                neighbour_cell_id_t,...
                                neighbour_cell_type_t,...
                                neighbour_cell_scc_neighbour_t,...
                                neighbour_cell_caf_neighbour_t,...
                                centroid_cell_id,...
                                centroid_zcom,...
                                centroid_time,...
                                xdim,...
                                ydim,...
                                zdim,...
                                invasion_boundary,...
                                time_vector,...
                                struct_counter,...
                                t...
                                )

cell_object_label = bwlabeln(binary_all_cells_from_pixels,18);
unique_object_labels=unique(cell_object_label);
index=find(unique_object_labels==0);
unique_object_labels(index)=[];

[unique_object_labels,cell_object_label] = join_periodic_objects(cell_object_label,ydim,xdim);  
[unique_object_labels,cell_object_label] = object_relabeller(cell_object_label);
object_size = object_size_function(cell_object_label);

tissue = logical(zeros(ydim,xdim,zdim));
max_object_index=find(object_size==max(object_size));
index_all_tissue=find(cell_object_label==unique_object_labels(max_object_index));
tissue(index_all_tissue)=1;

tissue(:,:,1:zdim-invasion_boundary)=0;
possible_cell_neighbours=cells_from_pixels.*tissue;
unique_possible_neighbours=unique(possible_cell_neighbours(:));
unique_possible_neighbours=unique_possible_neighbours(unique_possible_neighbours>0);

invading_cell_neighbours = organotypic_single_cell_neighbours(...
    unique_possible_neighbours,...
    neighbour_cell_id_t,...
    neighbour_cell_type_t,...
    neighbour_cell_scc_neighbour_t,...
    neighbour_cell_caf_neighbour_t,...
    centroid_cell_id,...
    centroid_zcom,...
    centroid_time,...
    time_vector(t+1));
neighbours_struct(struct_counter,t).invading_cell_neighbours=invading_cell_neighbours;
end