function organotypic_feature_extraction(directory_input,directory_output,no_combinations,no_repeats,micron_scale,xdim,ydim,zdim,invasion_boundary,quantification_day)

mkdir(directory_output)
folder_names=[directory_input '*run*'];
folders=dir(folder_names);
isub = [folders(:).isdir];
index=find(isub==0);
folders(index)=[];

twelve_hour_intervals=[0:36:360]+1;
time_vector=[0,2880,5760,8640,11520,14400];

correct_index = folder_reordering(no_combinations,no_repeats,folders);
cell_count=[];
for combination_index=1:no_combinations
    struct_counter=0;
    centroid_invasion_struct(no_repeats)=struct('invasion', []);
    neighbours_struct(no_repeats,5)=struct('invading_cell_neighbours', []);
    fractured_object_struct(no_repeats,5)=struct('no_sccs',[],'no_cafs',[],'min_object_depth',[],'max_object_depth',[]);
    
    for repeat_index=no_repeats*(combination_index-1)+1:no_repeats*combination_index
        struct_counter=struct_counter+1;
        [...
          directory,...
          centroid_time,...
          centroid_cell_id,...
          centroid_cell_type,...
          centroid_xcom,...
          centroid_ycom,...
          centroid_zcom,...
          neighbour_MC_step,...
          neighbour_cell_id,...
          neighbour_cell_type,...
          neighbour_cell_scc_neighbour,...
          neighbour_cell_caf_neighbour,...
          pixel_files...
          ]...
          = data_loader(directory_input,folders,correct_index,repeat_index); 





        
        cell_count = cell_counter(cell_count,centroid_time,centroid_cell_type,struct_counter,combination_index);

        centroid_invasion_struct = organotypic_centroid_invasion(...
                                        centroid_cell_id,...
                                        centroid_cell_type,...
                                        centroid_time,...
                                        centroid_zcom,...
                                        invasion_boundary,...
                                        micron_scale,...
                                        twelve_hour_intervals,...
                                        centroid_invasion_struct,...
                                        struct_counter...
                                        );

        for t=4
            [...
            neighbour_cell_id_t,...
            neighbour_cell_type_t,...
            neighbour_cell_scc_neighbour_t,...
            neighbour_cell_caf_neighbour_t,...
            cells_from_pixels,...
            cell_types_from_pixels,...
            binary_all_cells_from_pixels,...
            centroid_zcom...
            ] = organotypic_neighbour_fracture_data_loader(...
                                            directory,...
                                            pixel_files,...
                                            neighbour_MC_step,...
                                            neighbour_cell_id,...
                                            neighbour_cell_type,...
                                            neighbour_cell_scc_neighbour,...
                                            neighbour_cell_caf_neighbour,...
                                            centroid_zcom,...
                                            t,...
                                            time_vector,...
                                            xdim,...
                                            ydim,...
                                            zdim...
                                            );

            [neighbours_struct,index_all_tissue] = ...
                organotypic_neighbour_structure_compiler(...
                                            neighbours_struct,...
                                            binary_all_cells_from_pixels,...
                                            cells_from_pixels,...
                                            neighbour_cell_id_t,...
                                            neighbour_cell_type_t,...
                                            neighbour_cell_scc_neighbour_t,...
                                            neighbour_cell_caf_neighbour_t,...
                                            centroid_cell_id,...
                                            centroid_zcom,...
                                            centroid_time,...
                                            xdim,...
                                            ydim,...
                                            zdim,...
                                            invasion_boundary,...
                                            time_vector,...
                                            struct_counter,...
                                            t...
                                            );

            fractured_object_struct = ...
                organotypic_fractured_object_compiler(...
                                         fractured_object_struct,...
                                         binary_all_cells_from_pixels,...
                                         cells_from_pixels,...
                                         cell_types_from_pixels,...
                                         index_all_tissue,...
                                         xdim,...
                                         ydim,...
                                         zdim,...
                                         micron_scale,...
                                         struct_counter,...
                                         t...
                                         );
        end
    end
    mat_file_save_name=fullfile(directory_output, ['neighbours_fractures_run' sprintf('%05lu',combination_index) '.mat']);
    save(mat_file_save_name,'neighbours_struct','fractured_object_struct','combination_index');
    mat_file_save_name=fullfile(directory_output, ['invasion_centroids_run' sprintf('%05lu',combination_index) '.mat']);
    save(mat_file_save_name,'centroid_invasion_struct','combination_index');
end;
mat_file_save_name=fullfile(directory_output,'cell_count.mat');
save(mat_file_save_name,'cell_count');


[invasion_stats_all_sccs,invasion_score,maximum_invasion] = invasion_stats_compiler(directory_output,no_combinations,no_repeats,quantification_day);
[tapering,mean_scc_neighbours] = organotypic_strand_statistics(directory_output,no_combinations,no_repeats,micron_scale,zdim,invasion_boundary,quantification_day);
no_fractured_objects = fractured_object_counter(directory_output,no_combinations,no_repeats,quantification_day);
cell_growth_rates = cell_growth_rate(directory_output,no_combinations,no_repeats,quantification_day);
[invasion_score_percentiles,maximum_invasion_percentiles,tapering_percentiles,mean_scc_neighbours_percentiles,fractured_object_percentiles,growth_rate_percentiles] = percentiles_calculator(invasion_score,maximum_invasion,tapering,mean_scc_neighbours,no_fractured_objects,cell_growth_rates,no_repeats,no_combinations);
mat_file_save_name=fullfile(directory_output, 'compiled_data.mat');
save(mat_file_save_name,'invasion_stats_all_sccs','invasion_score','maximum_invasion','tapering','mean_scc_neighbours','no_fractured_objects','cell_growth_rates','invasion_score_percentiles','maximum_invasion_percentiles','tapering_percentiles','mean_scc_neighbours_percentiles','fractured_object_percentiles','growth_rate_percentiles');

end