#ifndef ORGANOTYPICECMCONCENTRATIONUPDATE_EXPORT_H
#define ORGANOTYPICECMCONCENTRATIONUPDATE_EXPORT_H

    #if defined(_WIN32)
      #ifdef OrganotypicECMConcentrationUpdate_EXPORTS
          #define ORGANOTYPICECMCONCENTRATIONUPDATE_EXPORT __declspec(dllexport)
          #define ORGANOTYPICECMCONCENTRATIONUPDATE_EXPIMP_TEMPLATE
      #else
          #define ORGANOTYPICECMCONCENTRATIONUPDATE_EXPORT __declspec(dllimport)
          #define ORGANOTYPICECMCONCENTRATIONUPDATE_EXPIMP_TEMPLATE extern
      #endif
    #else
         #define ORGANOTYPICECMCONCENTRATIONUPDATE_EXPORT
         #define ORGANOTYPICECMCONCENTRATIONUPDATE_EXPIMP_TEMPLATE
    #endif

#endif
