#ifndef ORGANOTYPICCELLBOUNDARYECMPENETRATION_EXPORT_H 
#define ORGANOTYPICCELLBOUNDARYECMPENETRATION_EXPORT_H

    #if defined(_WIN32)
      #ifdef OrganotypicCellBoundaryECMPenetration_EXPORTS
          #define ORGANOTYPICCELLBOUNDARYECMPENETRATION_EXPORT __declspec(dllexport)
          #define ORGANOTYPICCELLBOUNDARYECMPENETRATION_EXPIMP_TEMPLATE
      #else
          #define ORGANOTYPICCELLBOUNDARYECMPENETRATION_EXPORT __declspec(dllimport)
          #define ORGANOTYPICCELLBOUNDARYECMPENETRATION_EXPIMP_TEMPLATE extern
      #endif
    #else
         #define ORGANOTYPICCELLBOUNDARYECMPENETRATION_EXPORT
         #define ORGANOTYPICCELLBOUNDARYECMPENETRATION_EXPIMP_TEMPLATE
    #endif

#endif




