#ifndef SPHEROIDECMCONCENTRATIONUPDATE_EXPORT_H
#define SPHEROIDECMCONCENTRATIONUPDATE_EXPORT_H

    #if defined(_WIN32)
      #ifdef SpheroidECMConcentrationUpdate_EXPORTS
          #define SPHEROIDECMCONCENTRATIONUPDATE_EXPORT __declspec(dllexport)
          #define SPHEROIDECMCONCENTRATIONUPDATE_EXPIMP_TEMPLATE
      #else
          #define SPHEROIDECMCONCENTRATIONUPDATE_EXPORT __declspec(dllimport)
          #define SPHEROIDECMCONCENTRATIONUPDATE_EXPIMP_TEMPLATE extern
      #endif
    #else
         #define SPHEROIDECMCONCENTRATIONUPDATE_EXPORT
         #define SPHEROIDECMCONCENTRATIONUPDATE_EXPIMP_TEMPLATE
    #endif

#endif
